# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-28 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('phone', models.CharField(max_length=16)),
                ('department', models.CharField(max_length=16)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
