# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-28 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': '\u59d3\u540d', 'verbose_name_plural': '\u59d3\u540d'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(max_length=16, verbose_name='\u90e8\u95e8'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=16, verbose_name='\u59d3\u540d'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=16, verbose_name='\u624b\u673a'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='\u85aa\u6c34'),
        ),
    ]
